menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/keon
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: keon.io
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-65209371-1

# Copyright Infomation
startyear: 2016
